config/routes.rb
Shoppingmall::Application.routes.draw do
  resources :brands
  root :to => 'brands#index'

  resources :categories
  root :to => 'categories#index'

  resources :products
  root :to => 'products#index'

  match 'products/products_id/brands', :action => 'product_brands', :controller => 'brands'
  match 'categories/brands', :action => 'category_brands', :controller => 'brands'
  match 'brands/categories', :action => 'brand_categories', :controller =>'categories'
  match '/categories/find', :controller => 'categories', :action => 'find'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :bags_brands, :cloths_brand, :fragrance_brands, :jewellery_brands, :shoes_brand
  belongs_to :product
  validates_presence_of :bags_brands
  validates_presence_of :cloths_brand
  validates_presence_of :fragrance_brands
  validates_presence_of :jewellery_brands
  validates_presence_of :shoes_brand
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :bags, :cloths, :fragrance, :jewellery, :shoes
  validates_presence_of :bags
  validates_presence_of :cloths
  validates_presence_of :fragrance
  validates_presence_of :jewellery
  validates_presence_of :shoes
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :brand, :category, :price, :quantity, :brand_id
  has_many_through :brands
  validates_presence_of :brand
  validates_presence_of :category
  validates_presence_of :price
  validates_presence_of :quantity
  validates_numericality_of :price
  validates_numericality_of :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :check_logged_in, :only => [:edit, :update]

  
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
  
  private
   def check_logged_in
       authenticate_or_request_with_http_basic("brands") do |username,password|
       username == "admin" && password == "priya"
   end
 end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :check_logged_in, :only => [:edit, :update]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end
  
 

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
  
  def find
    
      @finds = Category.find(:all,:conditions=> ["cloths= ?", params[:search_string]])
      @find = params[:search_string]
  end
  
private
   def check_logged_in
       authenticate_or_request_with_http_basic("categories") do |username,password|
       username == "admin" && password == "priya"
   end
 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :check_logged_in, :only => [:edit, :update]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
 end
private
   def check_logged_in
       authenticate_or_request_with_http_basic("products") do |username,password|
       username == "admin" && password == "priya"
   end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cloths_brand %><br />
    <%= f.text_field :cloths_brand %>
  </div>
  <div class="field">
    <%= f.label :shoes_brand %><br />
    <%= f.text_field :shoes_brand %>
  </div>
  <div class="field">
    <%= f.label :jewellery_brands %><br />
    <%= f.text_field :jewellery_brands %>
  </div>
  <div class="field">
    <%= f.label :bags_brands %><br />
    <%= f.text_field :bags_brands %>
  </div>
  <div class="field">
    <%= f.label :fragrance_brands %><br />
    <%= f.text_field :fragrance_brands %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th>Cloths brand</th>
    <th>Shoes brand</th>
    <th>Jewellery brands</th>
    <th>Bags brands</th>
    <th>Fragrance brands</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.cloths_brand %></td>
    <td><%= brand.shoes_brand %></td>
    <td><%= brand.jewellery_brands %></td>
    <td><%= brand.bags_brands %></td>
    <td><%= brand.fragrance_brands %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cloths brand:</b>
  <%= @brand.cloths_brand %>
</p>

<p>
  <b>Shoes brand:</b>
  <%= @brand.shoes_brand %>
</p>

<p>
  <b>Jewellery brands:</b>
  <%= @brand.jewellery_brands %>
</p>

<p>
  <b>Bags brands:</b>
  <%= @brand.bags_brands %>
</p>

<p>
  <b>Fragrance brands:</b>
  <%= @brand.fragrance_brands %>
</p>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cloths %><br />
    <%= f.text_field :cloths %>
  </div>
  <div class="field">
    <%= f.label :shoes %><br />
    <%= f.text_field :shoes %>
  </div>
  <div class="field">
    <%= f.label :jewellery %><br />
    <%= f.text_field :jewellery %>
  </div>
  <div class="field">
    <%= f.label :bags %><br />
    <%= f.text_field :bags %>
  </div>
  <div class="field">
    <%= f.label :fragrance %><br />
    <%= f.text_field :fragrance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/find.html.erb
<h1>found categories for <%= @find %></h1>

<table>
  <tr>
    <th>Cloths</th>
    <th>Shoes</th>
    <th>Jewellery</th>
    <th>Bags</th>
    <th>Fragrance</th>
   
  </tr>

<% for category in @finds %>
  <tr>
    <td><%= category.cloths %></td>
    <td><%= category.shoes %></td>
    <td><%= category.jewellery %></td>
    <td><%= category.bags %></td>
    <td><%= category.fragrance %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Cloths</th>
    <th>Shoes</th>
    <th>Jewellery</th>
    <th>Bags</th>
    <th>Fragrance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.cloths %></td>
    <td><%= category.shoes %></td>
    <td><%= category.jewellery %></td>
    <td><%= category.bags %></td>
    <td><%= category.fragrance %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cloths:</b>
  <%= @category.cloths %>
</p>

<p>
  <b>Shoes:</b>
  <%= @category.shoes %>
</p>

<p>
  <b>Jewellery:</b>
  <%= @category.jewellery %>
</p>

<p>
  <b>Bags:</b>
  <%= @category.bags %>
</p>

<p>
  <b>Fragrance:</b>
  <%= @category.fragrance %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppingmall</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
    <span style= "text-align :right">
    <%= form_tag"/categories/find" do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag "search" %>
    <% end %>
    </span>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Brand</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.category %></td>
    <td><%= product.price %></td>
    <td><%= product.quantity %></td>
    <td><%= product.brand %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @product.category %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @product.quantity %>
</p>

<p>
  <b>Brand:</b>
  <%= @product.brand %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>